### ISSUE TITLE
CCD formatting issues

### ISSUE THREAD

**Issue by ccwhite333** [IsantePlus/openmrs-module-xds-sender#50]
- [x] fix the sorting by date on the ccd

- [x] fix the columns to wrap overflow text
- [x] change the dates to readable format
- [x]  all null values should appear as empty string/no text
- [x] remove the 'true' in medications

**Comment by stansL** [comment]
@pmanko , noticed from the implementation that the sorting by date is already in place for the vital signs and the encounters, are there any other fields that need sorting apart from these two?

**Comment by pmanko** [comment]
@stansL the PR does not address the Date sorting, correct?
